### ISSUE TITLE
Unable to use static build on Linux/Macos

### ISSUE THREAD

**Issue by theirix** [lasote/conan-libxml2#2]
Hello!
I noticed that a commit a7bb3f315c8dfc41f2f7f995914503d0b23b30 forces use of shared libxml2 even for Linux and Macos while it's a totally possible scenario to use a `libxml2.a`. Could you please check it?

**Comment by lasote** [comment]
Sure, I'll check it. Thanks

**Comment by lasote** [comment]
Please, try now and let  me know if you have any problem.

**Comment by theirix** [comment]
Thanks, it builds now with a static library. Please not that travis build on mac is failing.

**Comment by theirix** [comment]
Forgot to add. libxml2 autodetects lzma so it `--without-lzma` should be specifically passed to configure script.

**Comment by lasote** [comment]
Hi @theirix. I've pushed a new recipe with the --without-lzma and fixed the mac builds. Thanks for notice it. 
In a several minutes will be available.

**Comment by theirix** [comment]
Thanks, @lasote! Just updated with a binary package. It works perfectly.
