### ISSUE TITLE
Missing prebuilt package for 'libxml2/2.9.3@lasote/stable'

### ISSUE THREAD

**Issue by sixten-hilborn** [lasote/conan-libxml2#4]
Hi,

I get this error when trying to build my package which depends on libxml2:

```
WARN: Can't find a 'libxml2/2.9.3@lasote/stable' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MT, compiler.version=12, os=Windows
- Options: shared=True, libiconv:shared=False, zlib:shared=False
ERROR: Missing prebuilt package for 'libxml2/2.9.3@lasote/stable'
Try to build it from sources with "--build libxml2"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

However I find two packages that matches these settings with: `conan search -r=conan.io libxml2/2.9.3@lasote/stable -q 'arch=x86_64 AND build_type=Release AND compiler="Visual Studio" AND compiler.version=12 AND compiler.runtime=MT AND os=Windows'`

Does the libxml2 package need a rebuild? Why are there two packages with the same settings?

**Comment by mcraveiro** [comment]
This package used to work just fine for me but appears to have gone missing recently - all my windows builds have gone red.

**Comment by sixten-hilborn** [comment]
The package is still available at conan-transit: https://bintray.com/conan/conan-transit/libxml2%3Alasote
However it's not compatible with Conan 1.0 since it's using the now removed `ConfigureEnvironment`. That's probably why your builds went red.

The bincrafters packages are generally up to date, I'm actually already using `libxml2/2.9.3@bincrafters/stable` which works fine, so I'll close this issue.
Regarding conan-transit I think it should be avoided since many (most?) packages are incompatible with Conan 1.0 and they won't be updated as conan-transit is read-only.
